config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', as: :logout

  resource :user, only: :destroy do
    get 'retire'
  end
  resources :post, except: :index do
    resources :tickets, only: [:new, :create, :destroy]
  end
  match '*path' => 'application#error404', via: :all

end

app/models/post.rb
class Post < ActiveRecord::Base
	mount_uploader :post_image, PostImageUploader
	validates: :name length: { maximmum: 50 },presence: true
	validates: :content length: { maximmum: 1000 },presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :created_posts,class_name: 'Post', foreign_key: :owner_id
	
	def self.find_or_create_from_auth_hash(auth_hash)
	    provider = auth_hash[:provider]
	    uid = auth_hash[:uid]
	    nickname = auth_hash[:info][:nickname]
	    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
      end
    end
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  private
  
  def current_user
  	ruturn unless session[:user_id]
  	@current_user ||=User.find(session[:user_id])
  end


  def logged_in?
  	!!session[:user_id]  	
  end

  def authenticate
  	return if logged_in?
  	redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate, except: :show

	def show 
		@post = Event.find(params[:id])
	end

	def new 
		@post = current_user.created_posts.build
	end

	def create
		@post = current_user.created_posts.build(post_params)
		if @post.save
			redirect_to @post, notice: 'post your work!!'
		else
			render :new
		end
	end

	private

	def post_params
		params.require(:post).permit(
			:name, :content, :post_image
			)
	end
end

app/controllers/sessions_controller.rb
# -*- coding: utf-8 -*-
class SessionsController < ApplicationController
	def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

    def destroy
      reset_session
      redirect_to root_path, notice: 'ログアウトしました'
    end

    def failure
      redirect_to root_url, alert: "ログインに失敗しました"
    end
  end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  before_action :authenticate

  def retire
  end

  def destroy
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: 'you withdrawned'
    else
      render :retire
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portrait</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'AwesomeEvents', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Post your work', new_post_path %></li>
            <% if logged_in? %>
              <li><%= link_to 'Withdraw', retire_user_path %></li>
              <li><%= link_to 'logout', logout_path %></li>
            <% else %>
              <li><%= link_to 'Twitter login', '/auth/twitter' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>

<div class="container">
	 <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
<%= yield %>
</div>

</body>
</html>

app/views/posts/new.html.erb
<% now = Time.zone.now %>

<div class="page-header">
  <h1>Post your works</h1>
</div>

<%= form_for(@post, class: 'form-horizontal', role: 'form', html: { multipart: true }) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if @post.post_image? %>
      <div class="thumbnail">
        <%= image_tag @post.post_image.url %>
      </div>
    <% end %>
    <%= f.file_field :post_image %>
    <%= f.hidden_field :post_image_cache %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', row: 10 %>
  </div>

  <%= f.submit 'Post', class: 'btn btn-default', data: { disable_with: 'posting…' } %>
<% end %>

app/views/posts/show.html.erb
<div class="page-header">
  <h1>
    <%= @post.name %>
  </h1>
</div>
<div class="row">
  <div class="col-md-8">
    <% if @post.post_image? %>
      <div class="thumbnail">
        <%= image_tag @post.post_image.url %>
      </div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">
        主催者
      </div>
      <div class="panel-body">

      <% #あとで修正　%>
     <% if @post.owner %> 
          <%= link_to(url_for_twitter(@post.owner)) do %>
            <%= image_tag @post.owner.image_url %>
            <%= "@#{@post.owner.nickname}" %>
          <% end %>
        <% else %>
          退会したユーザです
        <% end %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        Detail
      </div>
      <div class="panel-body">
        <%= @post.content %>
      </div>
    </div>
  </div>

  
  <div class="col-md-4">
    <% if @post.created_by?(current_user) %>
      <%= link_to 'イベントを編集する', edit_post_path(@post), class: 'btn btn-info btn-lg btn-block' %>
      <%= link_to 'イベントを削除する', post_path(@post), class: 'btn btn-danger btn-lg btn-block', method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% end %>
    <% if @ticket %>
      <%= link_to '参加をキャンセルする', post_ticket_path(@post, @ticket), method: :delete, class: 'btn btn-warning btn-lg btn-block' %>
    <% elsif logged_in? %>
      <button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#createTicket">
        参加する
      </button>
      <div class="modal fade" id="createTicket" tabindex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="dialogHeader">参加コメント</h4>
            </div>
            <%= form_for(@event.tickets.build, url: event_tickets_path(@event), remote: true) do |f| %>
              <div class="modal-body">
                <%= f.text_field :comment, class: 'form-control' %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
                <%= f.button '送信', class: 'btn btn-primary', data: { disable_with: '送信中…' } %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to '参加する', new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block" %>
    <% end %>
    <hr>
    <div class="panel panel-default">
      <div class="panel-heading">
        参加者
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <% @tickets.each do |ticket| %>
            <% if ticket.user %>
              <li>
                <%= link_to(url_for_twitter(ticket.user)) do %>
                  <%= image_tag ticket.user.image_url, width: 20, height: 20 %>
                  <%= "@#{ticket.user.nickname}" %>
                <% end %>
                <%= ticket.comment %>
              </li>
            <% else %>
              退会したユーザです
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/retire.html.erb
<div class="page-header">
  <h1>Withdraw Confirmation</h1>
</div>
<% if current_user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<hr>
<%= link_to 'Withdraw', user_path, method: :delete, class: 'btn btn-danger' %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

	